name: 'Graphql Schema Check and Publish'
description: 'Set up the environment for a specific schema'

inputs:
  graph:
    description: 'The graph to set up'
    required: true
  schema_path:
    description: 'The schema path to set up and publish'
    required: true
  readme_path:
    description: 'The readme file path'
  schema_template:
    description: 'Boolean flag to determine to use template schema'\
    default: 'true'

runs:
  using: 'composite'
  steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Initialize Schema
      shell: bash
      run: |
        touch output.graphqls

        # Access the schema from the code repo
        cat ${{ github.workspace }}/${{ inputs.schema_path }} >> output.graphqls
      

    - name: Apply Action Template to Code Schema
      if: inputs.schema_template
      shell: bash
      run: |
        # Access the template from the action repo
        cat ${{ github.action_path }}/template/template.graphqls >> output.graphqls

    - name: Output Schema
      shell: bash
      run: |  
        cat output.graphqls

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "lts/*"

    - name: Install Cosmo CLI
      shell: bash
      run: |
        npm install -g wgc@latest

    - name: Run subgraph check
      shell: bash
      run: |
        wgc subgraph check ${{ inputs.graph }} --schema output.graphqls
      env:
        COSMO_API_KEY: ${{ env.COSMO_API_KEY }}

    - name: Run subgraph readme update
      if: inputs.readme_path
      shell: bash
      run: |
        wgc subgraph update ${{ inputs.graph }} --readme ${{ inputs.readme_path }}
      env:
        COSMO_API_KEY: ${{ env.COSMO_API_KEY }}

    - name: Run subgraph publish
      shell: bash
      run: |
        wgc subgraph publish ${{ inputs.graph }} --namespace default --schema output.graphqls
      env:
        COSMO_API_KEY: ${{ env.COSMO_API_KEY }}