name: 'SonarQube Publish'
description: 'Publish build to sonarqube'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache SonarQube packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Copy Maven settings.xml
      shell: bash
      run: |
        cat ~/.m2/settings.xml
        echo ${{ env.POM_SETTINGS_XML }}
        echo ${{ env.POM_SETTINGS_XML }} > ~/.m2/settings.xml
        sed -i "s/\${env.GITHUB_TOKEN}/${{ env.GITHUB_TOKEN }}/g" ~/.m2/settings.xml
        cat ~/.m2/settings.xml 

    - name: Build and analyze
      shell: bash
      env:
        SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

    - name: Publish package
      shell: bash
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}