name: 'SonarQube Publish'
description: 'Publish build to sonarqube'

inputs:
  default-xml-setting:
    description: 'Conditional to make not execute xml settings change'
    required: true
    default: 'false'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4.4.0
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - uses: s4u/maven-settings-action@v2.3.0
      with:
        servers: |
          [{
              "id": "github",
              "username": "${{ env.MAVEN_USERNAME }}",
              "password": "${{ env.MAVEN_TOKEN }}"
          }]
        repositories: |
          [{
              "id": "github",
              "url": "https://maven.pkg.github.com/flowrms/flow-commons",
              "snapshots": {"enabled":true}
          }]

    - name: Cache SonarQube packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build and analyze
      env:
        SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
      shell: bash
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
