name: 'Set Environment and other requires variables'
description: 'Set environment and other requires variables based on branch'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - name: Set ENVIRONMENT
      shell: bash
      run: |
        if [ "${{ github.ref }}" == 'refs/heads/production' ]; then
          echo "environment=production-2" >> $GITHUB_ENV
          echo "KUBE_CLUSTER_NAME=${{ env.KUBE_CLUSTER_NAME_PRODUCTION_2 }}" >> $GITHUB_ENV
        elif [ "${{ github.ref }}" == 'refs/heads/main' ]; then
          echo "environment=production" >> $GITHUB_ENV
          echo "KUBE_CLUSTER_NAME=${{ env.KUBE_CLUSTER_NAME_PRODUCTION }}" >> $GITHUB_ENV
        elif [[ "${{ github.ref }}" == 'refs/heads/staging' ]]; then
          echo "environment=staging" >> $GITHUB_ENV
          echo "KUBE_CLUSTER_NAME=${{ env.KUBE_CLUSTER_NAME_STAGING }}" >> $GITHUB_ENV
        elif [[ "${{ github.ref }}" == 'refs/heads/development' ]]; then
          echo "environment=development" >> $GITHUB_ENV
          echo "KUBE_CLUSTER_NAME=${{ env.KUBE_CLUSTER_NAME_DEVELOPMENT }}" >> $GITHUB_ENV
        elif [[ "${{ github.ref }}" == 'refs/heads/beta' ]]; then
          echo "environment=beta" >> $GITHUB_ENV
          echo "KUBE_CLUSTER_NAME=${{ env.KUBE_CLUSTER_NAME_BETA }}" >> $GITHUB_ENV
        else
          echo "environment=development" >> $GITHUB_ENV
          echo "KUBE_CLUSTER_NAME=${{ env.KUBE_CLUSTER_NAME_DEVELOPMENT }}" >> $GITHUB_ENV
        fi
        
    - name: Set IMAGE_TAG
      shell: bash
      run: |
        echo "IMAGE_TAG=ghcr.io/${GITHUB_REPOSITORY@L}-${{ env.environment }}:${{ github.sha }}" >> $GITHUB_ENV

    - name: Output variables
      shell: bash
      run: |
        echo "ENVIRONMENT: ${{ env.environment }}"
        echo "IMAGE_TAG: ${{ env.IMAGE_TAG }}"
        echo "KUBE_CLUSTER_NAME: ${{ env.KUBE_CLUSTER_NAME }}"