name: 'Set Environment and Image Tag'
description: 'Set environment and image tag based on branch'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - name: Set ENVIRONMENT and IMAGE_TAG
      shell: bash
      run: |
        if [ "${{ github.ref }}" == 'refs/heads/main' ]; then
          echo "ENVIRONMENT=production" >> $GITHUB_ENV
        elif [[ "${{ github.ref }}" == 'refs/heads/staging' ]]; then
          echo "ENVIRONMENT=staging" >> $GITHUB_ENV
        else
          echo "ENVIRONMENT=development" >> $GITHUB_ENV
        fi
        
        echo "IMAGE_TAG=ghcr.io/flowrms/flow-backend-${{ env.ENVIRONMENT }}:${{ github.sha }}" >> $GITHUB_ENV

    - name: Output variables
      run: |
      echo "ENVIRONMENT: ${{ env.ENVIRONMENT }}"
      echo "IMAGE_TAG: ${{ env.IMAGE_TAG }}"