name: 'Docker Build'
description: 'Build docker image and push container registry with environment support (development, staging, production)'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ env.WORKFLOW_TOKEN }}

    - name: Set Environment
      uses: flowrms/flow-commons-github/.github/actions/github-set-env@main

    - name: Override Maven Settings
      shell: bash
      run: |
        sed -i 's/$POM_XML_SETTINGS_PASSWORD/'"${{ env.MAVEN_TOKEN }}"'/' .m2/settings.xml
        sed -i 's/$POM_XML_SETTINGS_USERNAME/'"${{ env.MAVEN_USERNAME }}"'/' .m2/settings.xml
        cat .m2/settings.xml

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.IMAGE_TAG }}
        build-args: |
          ENVIRONMENT=${{ env.ENVIRONMENT }}

branding:
  icon: 'docker'
  color: 'cyan'
